### ISSUE TITLE
The report html file references a css which doesn't exist

### ISSUE THREAD

**Issue by matthieuRicaudDussarget** [xspec/xspec-maven-plugin-1#1]
In the target/xspec-reports directory, the html report files are referencing this css : 
`<link rel="stylesheet" type="text/css" href="file:/xspec/reporter/test-report.css"></link>`

This css doesn't exist, so the html preview of the file is quite poor and the diff between x:context and x:expect is not readable.

I think the reference should be relative, and test-report.css should be copied somewhere in the targer directory ?

**Comment by cmarchand** [comment]
Corrected in 1.5.0-RC1
Commit #4cb5c0f
Synchro to Maven Central expected on 2017-02-15

CSS wasn't extracted. Maybe we could write a new one, but it's for another day...
CSS reference is now a relative URI.

**Comment by matthieuRicaudDussarget** [comment]
Works fine ! Thanks a lot @cmarchand
