### ISSUE TITLE
xspec report index.html is wrong when some test are "Missed"

### ISSUE THREAD

**Issue by mricaud** [xspec/xspec-maven-plugin-1#13]
Hi, 

I noticed that when some xspec test are missed, the index.html in target/xspec-reports is wrong: 
The missed xspec file is not displayed on the first column, but it seems its result line is diplayed, which generate a shift in the table. 
It looks like another test has failed, which made me confused a couple of times :)

In the attached zip example [20171226_xspec-issue13.zip](https://github.com/xspec/xspec-maven-plugin-1/files/1587450/20171226_xspec-issue13.zip), I get this table: 
(tested with xspec-maven-plugin 1.5.1-RC6)

<table>
  <thead><tr><th>XSpec file</th><th>Passed</th><th>Pending</th><th>Failed</th><th>Missed</th><th>Total</th></tr></thead>
  <tbody>
    <tr><td colspan="6">/path/to/src/test/xspec</td></tr>
    <tr><td>identity-1_foo.xspec</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td></tr>
    <tr><td>identity-1_test.xspec</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td></tr>
    <tr><td>identity-3_foobar.xspec</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td></tr>
  </tbody>
</table>

Whereas the correct expeted table would be:

<table>
  <thead><tr><th>XSpec file</th><th>Passed</th><th>Pending</th><th>Failed</th><th>Missed</th><th>Total</th></tr></thead>
  <tbody>
    <tr><td colspan="6">/path/to/src/test/xspec</td></tr>
    <tr><td>identity-1_foo.xspec</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td></tr>
    <tr><td>identity-1_test.xspec</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td></tr>
    <tr><td>identity-2_test.xspec</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td></tr>
    <tr><td>identity-3_foobar.xspec</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td></tr>
  </tbody>
</table>

Since identity-2_test.xspec is the only "Missed" test, all others tests are "Passed".

**Comment by cmarchand** [comment]
Problem identified.

**Comment by cmarchand** [comment]
Solved in commit #ca69683

**Comment by cmarchand** [comment]
Solved in 1.5.1-RC7

**Comment by mricaud** [comment]
Hi Christophe, 
Thanks for the resolution, it used to work fine in 1.5.1-RC7, but in the latest Release 2.0.0-RC3 seems to have a regression because, the problem re-appeared (with the same test zip here)

I can't reopen this issue, shall I open a new one or can you please re-open it ?

Cheers

**Comment by cmarchand** [comment]
Re-open

**Comment by cmarchand** [comment]
Solved in 2.0.0-RC6
