### ISSUE TITLE
adhere to maven surefire property testFailureIgnore

### ISSUE THREAD

**Issue by rwalravens** [xspec/xspec-maven-plugin-1#16]
> Surefire report is generated from the XSpec report, via a XSL. At this time, transformation should be improved, to have a good report in Jenkins. Any help will be appreciated.

When building with Jenkins, and there are xspec test failures, the build is aborted and marked as "Failed". The "Test Result" screen, with the generated surefire report, is not available.

For regular builds with jenkins, we use the maven property `-Dmaven.test.failure.skip=true`. If there are test failures, the build continues, but at the end it is marked as "Unstable", and the surefire report is visible in the "Test Result" screen.

Could you take this [parameter](https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#testFailureIgnore) into account?

Kind regards

**Comment by cmarchand** [comment]
I think this can be done easily.
What is your expected deliver date ? May I keep this for a 2.0.0 (few weeks), or should I put this in a 1.5.2 ?

**Comment by rwalravens** [comment]
We're targeting end of this month, so we can wait for 2.0.0.

Kind regards

**Comment by rwalravens** [comment]
Thanks for implementing this parameter.
Unfortunately, I made a mistake in my orginal post: the surefire parameter is `maven.test.failure.ignore`.
Could you still adapt this please?

Kind regards

**Comment by cmarchand** [comment]
Release 2.0.0-RC3

**Comment by rwalravens** [comment]
In 2.0.0-RC6 and 2.0.0-RC7 build always fails with
`While running XSpecs: Some XSpec tests failed or were missed!`

I tried:

- `mvn clean install -Dmaven.test.failure.ignore=true`
- hardcoding in the plugin configuration: `<testFailureIgnore>true</testFailureIgnore>`

**Comment by cmarchand** [comment]
Correct, I changed Exception handling. Thanks for pointing this out.

**Comment by cmarchand** [comment]
Solved by commit (#19c74f1)[https://github.com/xspec/xspec-maven-plugin-1/commit/19c74f1a13e99b1a0a9e20ddb6523dc62dd85d68]
Will be available in 2.0.0-RC8, scheduled for 2020-04-22

**Comment by rwalravens** [comment]
Validated!
