### ISSUE TITLE
POM depends on a snapshot of a Maven plugin

### ISSUE THREAD

**Issue by bertfrees** [xspec/xspec-maven-plugin-1#18]
In order to be able to build xspec-maven-plugin I first needed to do the following steps:

```sh
git clone https://github.com/openam-org-ru/maven-external-dependency-plugin
cd maven-external-dependency-plugin/maven-external-dependency-plugin
mvn clean install
```

**Comment by cmarchand** [comment]
Solved in commit [8bbabcd](https://github.com/xspec/xspec-maven-plugin-1/commit/8bbabcdc44f02c9b346fc99894f20b044661c718)
Will be available for 2.0.0-RC7 or 2.0.0
