### ISSUE TITLE
Schematron: error with foreign elements

### ISSUE THREAD

**Issue by jimetevenard** [xspec/xspec-maven-plugin-1#19]
I tried to perform an XSpec test on a Schematron.

But an XPathException is thrown when the Schematron has a foreign element (An XSL instruction, for example)  
Test case : <https://github.com/labo-jim/xspec-schematron-fail>

## The cause

After  a one-day-long search, I found the cause :

The Shematrons's Skeleton XSLT implementation has a parameter, called `$allow-foreign`, which is used to tell the process that foreign elements are allowed or not.

This parameter is expected (although not typed) to be supplied as a string :
[Declaration](https://github.com/Schematron/schematron/blob/e16ecc490f9c6429f275ea268279787a71ff298f/trunk/schematron/code/iso_schematron_skeleton_for_saxon.xsl#L465) - [reference in a string comparison](https://github.com/Schematron/schematron/blob/e16ecc490f9c6429f275ea268279787a71ff298f/trunk/schematron/code/iso_schematron_skeleton_for_saxon.xsl#L1919) 

So,

## The solution I suggest

[The line below](https://github.com/xspec/xspec-maven-plugin-1/blob/174f8e6177432855cd64a37bb7c0667e3152d6b7/src/main/java/uk/org/adamretter/maven/XSpecMojo.java#L918) : `step3.setParameter(new QName("allow-foreign"), new XdmAtomicValue(true));` 

Should be : `step3.setParameter(new QName("allow-foreign"), new XdmAtomicValue("true"));`   
with *true* as a string.

## Pull Request

**If you're OK, I'll submit a PR very soon.**

**Comment by cmarchand** [comment]
I'm waiting for your PR !
;-)
