### ISSUE TITLE
"Index" needed to navigate to all xspec report file

### ISSUE THREAD

**Issue by matthieuRicaudDussarget** [xspec/xspec-maven-plugin-1#2]
Would it be possible to have a index.html file in target/xspec-reports, so we can easily have a view of all xspec reports of the projet ?

**Comment by cmarchand** [comment]
It should !

**Comment by cmarchand** [comment]
An index is generated, and xspec compilation files are now organized in separate folders. Hence, if 2 xspec have the same name, the first one is not overwritten by the second one.
Commit #2e09193

**Comment by matthieuRicaudDussarget** [comment]
Thanks a lot @cmarchand  !
I see it work, but I have a problem to make the index file appear at the moment (don't know what's happen?)

Anyway in my former test I noticed that the links from the index to the files are absolute.
Could you make them relativ ?

By the way, that's a quite good idea that the index give a summary table of the test (I did not expect so much :)) 
As attached file, I tried to make the index a bit better look : 
- using the default report css style
- using colors to embed failed report
It needs changing the xsl, which I can do if you like.

I'm not able to re-open, I let you see if you agree.

**Comment by matthieuRicaudDussarget** [comment]
@cmarchand, the index is created only if every xspec is successfull, there must be something wrong as we've seen together.

**Comment by cmarchand** [comment]
1.5.0-RC6 published to fix this.

**Comment by matthieuRicaudDussarget** [comment]
Works find ! Thank you Christophe !
What about enhancement of the css of this page, should I add another request ?

**Comment by cmarchand** [comment]
I kindly accept contributions, especially on CSS / styling parts, where I'm a noob !
Do not hesitate to create pull requests !
;)

**Comment by matthieuRicaudDussarget** [comment]
I'll do :)
