### ISSUE TITLE
Change excludes param to work as in other plugins

### ISSUE THREAD

**Issue by cmarchand** [xspec/xspec-maven-plugin-1#28]
Today, `exclude` parameter excludes all pathes that **ends with** the exclude value. This is not convinient, and should be changed, to be like in [maven-compiler-plugin](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#excludes).

**Comment by cmarchand** [comment]
Solved in [issue_24 9abf722]

**Comment by cmarchand** [comment]
Code has to be tested under windows. It may miss some \\ ...

**Comment by adamzkover** [comment]
Shouldn't the exclude pattern be relative to testDir? For example, if a file is created at src/test/resources/filesToTest/imported.xspec, testFilenameWithoutWildCharBasedExclusions shouldn't fail, since the "imported.xspec" pattern would exclude this new file?
