### ISSUE TITLE
Result xml files are created at the root of the project

### ISSUE THREAD

**Issue by matthieuRicaudDussarget** [xspec/xspec-maven-plugin-1#3]
When using scenario that referencies context and expect in an external file such as :
``` xml
<x:scenario label="test">
    <x:context href="input.xml"/>
    <x:expect label="OK" select="/*" href="output-expected.xml"/>
</x:scenario>
```
Then (it seems) the XSPEC process creates an external file for the result (e.g. "d145.xml").
If there are diff, the report doesn't display it but give a html link to each file. I'm not sure when and when it happens (but this is also the case using a tool like oXygen).

Anyway theses files are created at the root of the project (at pom.xml level) and I guess it would be better if those files were created somewhere in the target directory (within surefire-reports or xspec-reports directory ?)

**Comment by cmarchand** [comment]
@cirulls : do you think this should be corrected in default implementation ? In my opinion, temporary xml files should be put in the same directory than the compiled XSL, it would be easier to clean.

**Comment by cirulls** [comment]
Sorry for the late reply. 

I would need a bit more context to understand this issue. Is this issue related to XSpec or the the XSpec maven plugin? 

Following @matthieuRicaudDussarget's example, I tried to run the following XSpec test using XSpec from the command line but didn't find any generated diff files (the associated XSLT ```intermediate.xsl``` performs an identity transform and ```intermediate.xml``` and ```intermediate-output-expected.xml``` are identical):

```xml
<x:description xmlns:x="http://www.jenitennison.com/xslt/xspec" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" stylesheet="intermediate.xsl">
	<x:scenario label="test">
		<x:context href="intermediate.xml"/>
		<x:scenario label="intermediate file">
			<x:expect label="OK" select="/*" href="intermediate-output-expected.xml"/>
		</x:scenario>
	</x:scenario>
</x:description>
```

If XSpec is executed via ant as within the Oxygen editor, I seem to recall that there may be some generated files in some cases and [the patch introduced by Oxygen](https://github.com/cmarchand/oxygen-xspec-patch/blob/master/build.xml#L70-L93) clean them up. However, I haven't tried this and don't know if this is related to this issue.

If this is an XSpec issue, can you specify how you run XSpec so that I can reproduce the issue? If it is a XSpec maven plugin issue I'm afraid I'm not very familiar with it and @cmarchand is probably the best person to answer this.

**Comment by cmarchand** [comment]
@matthieuRicaudDussarget : attached, a maven project to reproduce the problem.
Could you fix it to make the xspec succeed, and to view the problem ? My xspec always fail.
[xspec-issue3.zip](https://github.com/xspec/xspec-maven-plugin-1/files/809092/xspec-issue3.zip)

**Comment by matthieuRicaudDussarget** [comment]
@cmarchand : you need to add the attribute select="/*" on <x:expect>so your test works fine.
`<x:expect label="The expected file" select="/*" href="../resources/expected.xml"/>`

@cirulls : Sorry for my late reply too !
The test I made was directly with the maven plugin. 
I'm can't find when those files are generated or not, but I have a working code that has this behaviour.
I'll make this code clean in a zip to illustrate the case.

**Comment by cmarchand** [comment]
With release 1.5.0-RC2 of xspec-maven-plugin, the `identity.xml` file is generated in `target/xspec-reports/identity.xspec` :
```
target
└── xspec-reports
    ├── identity.xspec
    │   ├── identity.html
    │   ├── identity.xml
    │   └── xslt
    │       └── identity.xspec.xslt
    ├── index.html
    └── resources
        └── test-report.css
```
This sounds good to me.

Feel free to re-open this issue, if you find something new, or if I misunderstand.

**Comment by matthieuRicaudDussarget** [comment]
I finaly found the criterium that make those file being created (in oXygen or maven plugin) :
 **It depends on the size of the files to be compared !**

I guess if one of the xml files is to long then, the html report would be too long to load in the browser, so the implementation prefers giving a link to the file so the user can compare it with its own tool.

As attached file a zip with this behaviour 
[20170304_xspec-issue3.zip](https://github.com/xspec/xspec-maven-plugin-1/files/816313/20170304_xspec-issue3.zip)

I ran "mvn test" and let the files in the zip so you can see : 
- the html report with links
- the 2 files : d24.xml and d26.xml being created at the root folder

In the input ou output xml document you can delete one element <data> to see that those files are not created. After dichotomous test, it seems the limit is 335 elements.

It was not easy to fing this reason and sorry that I did not investigate more before.
So I guess this has nothing to do with the use of @href in context/expect.

I'm using XSPEC to do some kind of "Integration Test" more than Unit Test : giving a sample.xml I want to guarantee the XSLT generate the good output file.
That's why my files are longer than 335 elements in most cases and I get a lot of {generate-id()}.xml file at the root of all my projects.

@cmarchand I don't have the right to reopen this issue, would you do it for me ?

Thanks

**Comment by cmarchand** [comment]
Issue re-opened

**Comment by cmarchand** [comment]
This is a xspec bug, not a plugin bug.
Created here : https://github.com/xspec/xspec/issues/93

I close this issue as everything is in issue #93

**Comment by cmarchand** [comment]
Setting base output URI solves the problem.

**Comment by cmarchand** [comment]
Commit #88c6604
1.5.0-RC3
