### ISSUE TITLE
Schematron XSpecs generate temporary files in project folder

### ISSUE THREAD

**Issue by jbvalentin** [xspec/xspec-maven-plugin-1#34]
Hi, 

when a project with Schematron XSpec tests is built, several temporary files, named `context-<****>.xml` (where <****> is a computed id) are generated in the root folder holding holding the tests (typically the `src/test/xspec` folder). 

These files shouldn't be stored at that place, but rather at a dedicated temporary location, which would be automatically cleaned up when performing an `mvn clean`.

**Comment by AirQuick** [comment]
As for XSpec (not the XSpec Maven plugin), v1.4.0 or later no longer creates `context-*.xml` (xspec/xspec#549).

**Comment by cmarchand** [comment]
2.0.0-RC6 now uses 1.5.0 release of XSpec. This should be corrected.
At least, I can not see anymore temporary files.
