### ISSUE TITLE
[XSpec 1.5.0 support] Check steps chain for Schematron

### ISSUE THREAD

**Issue by cmarchand** [xspec/xspec-maven-plugin-1#39]
Support for XSpec 1.5.0 is engaged in branch issue_24.
Need to check if all steps implemented in shell in XSpec are correctly implemented in plugin for Schematron

**Comment by cmarchand** [comment]
Done

**Comment by AirQuick** [comment]
In XSpec v2.0.0, I'm going to concatenate 4 Schematron transformations into 1 stylesheet: xspec/xspec#912
Just FYI.

**Comment by cmarchand** [comment]
Ok, I'll rewrite all schematron processing according to shell / ant script.
Thanks for information
