### ISSUE TITLE
Multiple levels URI resolution with XML catalogs

### ISSUE THREAD

**Issue by AxelCourt** [xspec/xspec-maven-plugin-1#4]
Hi,

The XSpec plugin seems to resolve URI according to the specified catalog (configuration/catalogFile in the POM) only when they are at the "first importation level".
If A.xsl imports B.xsl, B.xsl is resolved by looking in the catalog.
But if A.xsl imports B.xsl and B.xsl imports C.xsl, C.xsl will not be resolved by looking in the catalog.

XML Catalog works in mysterious ways...

**Comment by cmarchand** [comment]
[issue4.zip](https://github.com/xspec/xspec-maven-plugin-1/files/838646/issue4.zip)
Attached test-case

**Comment by cmarchand** [comment]
This bug has been mentioned by

**Comment by cmarchand** [comment]
Solved in #276affa
I've been forced to change all the URI resolver that was used before.
Now, xspec resources are accessed via xspec:/ URI, and a catalog with rewritePrefix is dynamically generated to resolve to plugin jar file.
If you set a catalog in plugin configuration, it is added to generated catalog as a nextCatalog.

**Comment by cmarchand** [comment]
1.5.0-RC4 deployed in maven, wait 24 hours for synchronization into maven-central, and tell me if this solves your problem.

**Comment by cmarchand** [comment]
Catalog resolve is not available at exec time, only at compile time.

**Comment by cmarchand** [comment]
RC5 published, seems to solve every entries.
Close this issue.
Re-open it if solution is not complete.
