### ISSUE TITLE
Surefire reports are not written to correct location

### ISSUE THREAD

**Issue by rwalravens** [xspec/xspec-maven-plugin-1#40]
In 2.0.0-RC07
Surefire reports are written to the `reportDir` instead of `surefireReportDir`.
Probably typo in line 460 and 617 of `XSpecRunner.java`

Also the parameter `generateSurefireReport` is unused and defaults to `true` instead of the documented `false`.

**Comment by cmarchand** [comment]
It's in `surefire-reports` for xquery, and in `xspec-reports` for schematron and xsl.
Thanks for pointing this out.

**Comment by cmarchand** [comment]
Solved in commit (#39d441f)[https://github.com/xspec/xspec-maven-plugin-1/commit/39d441fb88ea399bd09d3f255ca0115335f986ae].

JUnit is not used anymore in xspec-maven-plugin, and surefire-reports are always generated. Parameter has been removed, and in-code documentation has been updated. Online documentation is not updated, and I've created an (issue for this)[https://github.com/xspec/xspec-maven-plugin-1/issues/43].

**Comment by cmarchand** [comment]
2.0.0-RC8 published

**Comment by rwalravens** [comment]
Validated!
