### ISSUE TITLE
No index.html generated

### ISSUE THREAD

**Issue by rwalravens** [xspec/xspec-maven-plugin-1#41]
In 2.0.0-RC6 and 2.0.0-RC7 I am not able to produce an `index.html` file.
Not when build fails, not when build succeeds.

**Comment by cmarchand** [comment]
I can not reproduce this use-case. Both with 2.0.0-RC6 and 2.0.0-RC7, I have an `index.html`

```
09:57 $ find target -name 'index.html'
target/xspec-reports/index.html
```
Could you please attach a project that reproduces the problem ?

**Comment by rwalravens** [comment]
It seems that the issue only manifests itself on Windows (our jenkins instance is running on debian).

![image](https://user-images.githubusercontent.com/36928442/79851660-e9a63000-83c5-11ea-9b48-0fab4a2b8b1b.png)

**Comment by cmarchand** [comment]
Ah ah ! I do not have a windows to test ! So, probably a `\` char somewhere...
I'm gonna took my wife's laptop to test.
Thanks.

**Comment by cmarchand** [comment]
Confirmed on a windows box, `index.html` is not generated.

**Comment by cmarchand** [comment]
Solved by commit (#ff34dc3)[https://github.com/xspec/xspec-maven-plugin-1/commit/ff34dc3b330e4bf6b1e2a0cafbe8c9409e4bc856].
Will be available in 2.0.0-RC8

**Comment by cmarchand** [comment]
2.0.0-RC8 published

**Comment by rwalravens** [comment]
Validated!
