### ISSUE TITLE
test-report.css seems to be cut off during the copy to the html reports folder

### ISSUE THREAD

**Issue by Glodenox** [xspec/xspec-maven-plugin-1#44]
It would appear that the test-report.css in the html output folder has been getting cut off at exactly 8 KB for quite a while now in the xspec-maven-plugin. Because browsers tend to make do with what they get, I hadn't noticed this any sooner than this. I see this happening on both Windows and Linux, so this doesn't seem to be platform-specific to me.

The most likely cause for this seems to be the `BufferedOutputStream` that doesn't get closed in [XSpecRunner.java](https://github.com/xspec/xspec-maven-plugin-1/blob/master/src/main/java/io/xspec/maven/xspecMavenPlugin/XSpecRunner.java#L860), but I haven't managed to test that.

**Comment by cmarchand** [comment]
2.0.0-RC8 published
