### ISSUE TITLE
XSpec 1.6.0 support

### ISSUE THREAD

**Issue by Glodenox** [xspec/xspec-maven-plugin-1#48]
The Maven plugin currently relies on XSpec 1.5.0. It would be great if it could be upgraded to 1.6.0 due to some of the features available there. I'm pretty certain this is a known thing, but I didn't see an issue about it yet, so I took the liberty to create one :)

Some quick testing showed me that most of my basic stuff seems to work after enabling the line-number extension function by uncommenting those two lines. I did afterwards run into issues identified by the ResolverTest though, so there seems to be more work to it than just that.

**Comment by fidothe** [comment]
It's worth noting that with Saxon 10.x, the bundled XSpec 1.5 errors out while compiling test files, which has been fixed in 1.6. So, it's completely impossible to use Saxon 10.1 or 10.2 (unsure about 10.0) with the the plugin.

**Comment by cmarchand** [comment]
I can not remember if it works or not, and I have no time to check now, but you can specify the XSpec release you want to use with the plugin :
```xml
  <plugin>
    <artifactId>xspec-maven-plugin</artifactId>
    <dependencies>
      <dependency>
        <groupId>io.xspec</groupId>
        <artifactId>xspec</artifactId>
        <version>1.6</version>
    ....
```

**Comment by fidothe** [comment]
Yup, that works! Thanks very much - hadn't occurred to me that would be possible... I will update the README and file a PR.

**Comment by cmarchand** [comment]
As I'm working to make xspec-maven-plugin compatible with XSpec 3.1.2, I close this one, outdated
