### ISSUE TITLE
Activation of XInclude for Saxon

### ISSUE THREAD

**Issue by nkutsche** [xspec/xspec-maven-plugin-1#5]
Hi all,

for some of my XSpec tests it was necessary to activate the Saxon XInclude processing (-xi). I did this in the Oxygen via the Ant parameter `saxon.custom.options` with the value `-xi`.

Now I try to use the same XSpec tests in Maven using this nice plugin here. Generally it works, but the tests fails, because the XInclude processing is not activated. As far as I see, there is no way to configure the plugin on the same way as I did it in Oxygen, is there?

Best Regards,
Nico

**Comment by cmarchand** [comment]
I'll add an option for this, as soon as possible.
Stay tuned !
Christophe

**Comment by cmarchand** [comment]
Could you provide a simple XSpec that should run correctly if such an option were available ? I have to add some unit tests...
Best

**Comment by cmarchand** [comment]
Give a try to 1.5.1-RC1, with this as configuration :
```
<configuration>
  <generateSurefireReport>true</generateSurefireReport>
  <saxonOptions>
    <xi>on</xi>
  </saxonOptions>
</configuration>
```

It should be available at 17:00 UTC on maven central.

**Comment by cmarchand** [comment]
I'll update the documentation later, for these new configuration options.

**Comment by cmarchand** [comment]
Documentation has been updated : https://github.com/xspec/xspec-maven-plugin-1/wiki

**Comment by nkutsche** [comment]
hi @cmarchand,

thanks for the implementation! I'm really sorry I couldn't help, but I was and actually I'm still on vacation so I'll give it a try when I'm back to my computer.

Best Regards, 
Nico
