### ISSUE TITLE
Not working with Saxon 10

### ISSUE THREAD

**Issue by aljopainter** [xspec/xspec-maven-plugin-1#52]
Probably not an "issue" in the sense that the product is not targetting Saxon 10, but I thought that I would mention the following. 

The function `x:saxon-version()` fails with Saxon 10 because the result of the call:

`x:extract-version(system-property('xsl:product-version'))`

fails because the version returned by `system-property('xsl:product-version')` returns a version number with a single '.' (i.e. 10.0).

**Comment by AirQuick** [comment]
Just for the record, `x:extract-version()` was fixed in xspec/xspec#844 and included in XSpec v1.6.0.

**Comment by aljopainter** [comment]
OK, thanks. 

I'll just have to wait for the next version of the XSpec Maven Plugin that uses 1.6.0.

**Comment by aljopainter** [comment]
Working now, thanks!
