### ISSUE TITLE
plugin execution fails under Saxon 10.x

### ISSUE THREAD

**Issue by fidothe** [xspec/xspec-maven-plugin-1#60]
While poking around because of the issue affecting me (#48) with Saxon 10.2, I've now checked with Saxon 10.0 and 10.1, under JDK 1.8 and 14, and it doesn't work because of how XSpec 1.5 tries to introspect the saxon version number, here:

https://github.com/xspec/xspec/blob/0754728f9bc1168955be88b62dede4e1064be1a8/src/compiler/generate-common-tests.xsl#L67-L70

The function it calls (`x:saxon-version`) assumes that it's a 4-part version number and 10.x are two-part... 

https://github.com/xspec/xspec/blob/0754728f9bc1168955be88b62dede4e1064be1a8/src/common/xspec-utils.xsl#L235

Anyway, I have no idea if XQuery xspec files can be compiled and run under Saxon 10.x, but I'm pretty sure that XSLT xspecs cannot, without upgrading the bundled XSpec to 1.6 😢 .

**Comment by cmarchand** [comment]
Probably outdated, as this file doesn't exist anymore in XSpec.

Currently working on XSpec 3.1.2 compatibility, re-open if I'm wrong
