### ISSUE TITLE
XSpec 2 support

### ISSUE THREAD

**Issue by thendarion** [xspec/xspec-maven-plugin-1#64]
with XSpec 2.0.7 the plugin says
```
[ERROR] Exception while creating XmlStuff
io.xspec.maven.xspecMavenPlugin.utils.XSpecPluginException: URI is not absolute
    at io.xspec.maven.xspecMavenPlugin.utils.XmlStuff.<init> (XmlStuff.java:212)
    at io.xspec.maven.xspecMavenPlugin.XSpecRunner.init (XSpecRunner.java:173)
    at uk.org.adamretter.maven.XSpecMojo.execute (XSpecMojo.java:369)
```
but it's working fine with XSpec 1.6.0

**Comment by AirQuick** [comment]
The plugin needs to address [the breaking changes](https://github.com/xspec/xspec/issues/1121#issue-668630717-permalink:~:text=For%20those%20who%20access%20XSpec%20internals).

**Comment by cmarchand** [comment]
The plugin does not support yet XSpec 2.0. That's plan for 2021 Q2.

**Comment by thendarion** [comment]
thx :)

**Comment by thendarion** [comment]
how's this update faring?

out of curiosity: which of the breaking changes need to be addressed in this plugin?

**Comment by cmarchand** [comment]
Hum... delays are expected ! I haven't start working on this.  
And I have no idea of any breaking changes.

I've plan go to a 2.x release, to align plugin version with xspec impl version, but at this point, no breaking change are identified.

**Comment by cmarchand** [comment]
Well : no breaking changes in plugin usage are identified.

List of XSpec breaking changes that must be addressed in plugin is quite important :
- compiler / reporter resource location have changed, and plugin must be updated
- compiling process has changed, XSL / XQuery have been removed, plugin must be updated
- plugin generates files outside of `src/test` directory, and it implies a lot of copying tasks, mainly
  if xspec file or XSL reference external resources via `document(...)` and similar functions
- coverage was not correctly supported, and it must be re-implemented correctly

**Comment by nkutsche** [comment]
Just as workaround until @cmarchand could handle this issue: my [alternative XSpec plugin](https://github.com/nkutsche/xspec-maven-plugin) supports now XSpec 2.0+.

**Comment by cmarchand** [comment]
Nice !
I have a version ready, but I'm waiting for @mricaud to deliver a new release of [XUT](https://github.com/mricaud/xml-utilities). I think I'm gonna publish my own fork of XUT, since Mat didn't publish anything since october...

**Comment by mricaud** [comment]
Hi @cmarchand I had problem with publishing new XUT version to Maven Central. I'll do my best and contact you.
Cheers

**Comment by mricaud** [comment]
Hi @cmarchand, [XUT 0.1.2](https://mvnrepository.com/artifact/org.mricaud.xml/xut/0.1.2) is now on Maven Cenral. Hope it's ok for you ?

**Comment by kirkilj** [comment]
Since @mricaud pushed XUT 0.1.2 to Maven Central, can this issue move across the finish line now?

**Comment by cmarchand** [comment]
Sorry for not having changed the status of this issue... It available since june 9th.
https://repo1.maven.org/maven2/io/xspec/maven/xspec-maven-plugin/2.1.4/
Christophe
