### ISSUE TITLE
Missing surefire reports due to tests targetting the same xslts

### ISSUE THREAD

**Issue by Glodenox** [xspec/xspec-maven-plugin-1#68]
If you have two or more xspec files targeting the same xslt, there will only be one surefire report available for that xslt. This is because the filename of the targeted xslt is used as the identifier to generate the surefire report for the test. As a solution, the xspec file path should be used as identifier, as that is guaranteed to be unique for each test.

This has caused automated builds to indicate as stable for us, even though xspec tests failed.

**Comment by cmarchand** [comment]
I've merged your PR, but I have securities issues and I'm not able publish a new release.

I'm waiting from Norm Walsh for explanation on how to migrate from XML Resolver 1.1 to 4.5 to solve this problem.

As soon as it ready, I publish a new release.

**Comment by cmarchand** [comment]
Release 2.2.0 published, just have to wait for sonatype synchro to maven central.

**Comment by cmarchand** [comment]
Available in Maven Central
