### ISSUE TITLE
Missing commons-io dependency

### ISSUE THREAD

**Issue by Glodenox** [xspec/xspec-maven-plugin-1#73]
We seem to be running into an issue when a project doesn't have a dependency on commons-io by itself:
> Execution default-cli of goal io.xspec.maven:xspec-maven-plugin:2.2.0:run-xspec failed: A required class was missing while executing io.xspec.maven:xspec-maven-plugin:2.2.0:run-xspec: org/apache/commons/io/output/NullOutputStream

I suspect this is a result of setting the Maven dependencies as provided in https://github.com/xspec/xspec-maven-plugin-1/commit/a433c1b24cf1fe9394effe0f425ed95805d4a08b. commons-io was a transitive dependency from maven-core via maven-shared-utils. I see only 3 uses of commons-io in the project, so either adding the dependency explicitly or removing those 3 uses would solve this issue.

> src/main/java/io/xspec/maven/xspecMavenPlugin/utils/XSpecCompiler.java:59
> src/main/java/io/xspec/maven/xspecMavenPlugin/XSpecRunner.java:38
> src/test/java/io/xspec/maven/xspecMavenPlugin/utils/ProcessedFileTest.java:31

**Comment by Glodenox** [comment]
As a temporary workaround, we've added the missing dependency to the plugin in our configuration:
```
          <dependencies>
            <dependency>
              <groupId>commons-io</groupId>
              <artifactId>commons-io</artifactId>
              <version>2.11.0</version>
            </dependency>
          </dependencies>
```

**Comment by adamretter** [comment]
Yes, I can confirm this is an issue.

This class imports Commons IO `NullOutputStream`: https://github.com/xspec/xspec-maven-plugin-1/blob/master/src/main/java/io/xspec/maven/xspecMavenPlugin/XSpecRunner.java#L38

But the dependency on commons-io is missing from `pom.xml`.

**Comment by adamretter** [comment]
I sent a fix for this - https://github.com/xspec/xspec-maven-plugin-1/pull/78
