### ISSUE TITLE
Compatibility with Saxon 11+

### ISSUE THREAD

**Issue by philippn** [xspec/xspec-maven-plugin-1#74]
Hi @cmarchand ,

I have been trying to update our infra to Saxon 11 and found that it doesn't seem to be compatible with the plugin at this time.

The issue seems to stem mainly from Saxon abandoning the `URIResolver` in favor of the `ResourceResolver`. Looking at https://github.com/xspec/xspec-maven-plugin-1/blob/master/src/main/java/io/xspec/maven/xspecMavenPlugin/utils/XmlStuff.java#L139 the call `xsltCompiler.getURIResolver()` returns `null` with Saxon 11 and this subsequently triggers a `NullPointerException`.

For reference, here is the stacktrace:

```
Caused by: java.lang.NullPointerException
	at io.xspec.maven.xspecMavenPlugin.resolver.Resolver.resolve(Resolver.java:96)
	at io.xspec.maven.xspecMavenPlugin.utils.XmlStuff.resolveSrc(XmlStuff.java:429)
	at io.xspec.maven.xspecMavenPlugin.utils.XmlStuff.createXsltExecutables(XmlStuff.java:270)
	at io.xspec.maven.xspecMavenPlugin.utils.XmlStuff.<init>(XmlStuff.java:148)
```

Thanks for your time and kind regards,
Philipp

**Comment by cmarchand** [comment]
You are probably correct.

I put this on my TODO list.

Christophe

**Comment by philippn** [comment]
Hi @cmarchand 

I have been looking at this issue from a couple of directions and just wanted to share my findings. I have a branch running that works with Saxon 9, 10, 11 and 12. You can find the relevant commit here: https://github.com/philippn/xspec-maven-plugin-1/commit/8b9f69d502cd0206a05d01f9eb68e0b9add2addb

Just a few notes regarding it:

My first impression was that it would be needed to have different setup code for the different Saxon versions, so I invented the Interface `ResolverDecorator` and subsequently had different implementations for it. As it turned out, that wasn't needed though because Saxon 11 and 12 still perfectly support the `URIResolver`; the only difference is that it is not initialized by default, i.e. `XsltCompiler#getURIResolver` returns null.

Essentially, this can be fixed by just initializing a `StandardURIResolver` instead and then using that as if it was supplied.

If you find the `ResolverDecorator` approach interesting, I can happily create a pull request for this solution. If you just want to go with the direct solution, it should be fixable with:

1. In https://github.com/xspec/xspec-maven-plugin-1/blob/master/src/main/java/io/xspec/maven/xspecMavenPlugin/utils/XmlStuff.java#L218 add a null-check for saxonResolver and if its null initialize it to `new StandardURIResolver()`
2. Change the test cases not compiling to instantiate the `StandardURIResolver` directly

Hope that helps!

Kind regards,
Philipp

**Comment by philippn** [comment]
One further note: From my testing, it seems to be important to continue compiling against Saxon 9.9 as long as you want it to be supported.

when compiled with Saxon 10 or 11, the code will fail with Saxon 9.9 in this place https://github.com/xspec/xspec-maven-plugin-1/blob/master/src/main/java/io/xspec/maven/xspecMavenPlugin/utils/XmlStuff.java#L501 with a NoSuchMethod error. The reason for this is, that the return type has changed with Saxon 10 and the new return type is more specific (a concrete class instead of iterator<>).

I have changed my branch accordingly back to 9.9 for the time being.

**Comment by cmarchand** [comment]
Thanks for your research !

I'm not sure it's required to support Saxon 9.9 anymore... I just have a look in XSpec Implementation, and [Saxon 9.9 is now deprecated](https://github.com/xspec/xspec/wiki/Requirements#saxon-98-and-99-are-deprecated).

So we can drop support for Saxon 9.9 in XSpec Maven Plugin.

Your `ResolverDecorator` solution is quite elegant, so I'm really interested in a pull request for this. Then a small refactoring to introduce a `ResolverDecoratorStrategy` **may** be interesting, but it depends on unit tests...

Thanks a lot for your work, I have not enough free-time to work on this now.

**Comment by philippn** [comment]
Hi @cmarchand,

I have opened a pull request with my current changes. Regarding the `ResolverDecoratorStrategy`, i dont quite understand what you mean. But if you elaborate, i could try helping out with that too.

Thanks for your time,
Philipp
