### ISSUE TITLE
Using internal Java resolver for Saxon

### ISSUE THREAD

**Issue by julienguiraud** [xspec/xspec-maven-plugin-1#8]
Hello,

We need to configure a Java resolver to launch the XSpec tests.
We find out that -r Saxon option allows it.
-r:classname from http://www.saxonica.com/documentation/#!using-xsl/commandline

Is it possible to add -r Saxon option in the plugin ?

Do you need a pull-request ?

Regards,
Julien

**Comment by cmarchand** [comment]
xspec-maven-plugin uses xmlresolver as URIResolver, mainly to make catalogs being used correctly.
If we allow to replace the URI reolver by another, the <catalog/> configuration property will become inefficient.
So, you could have un your plugin configuration two options that make them inconsistent ; I'd prefer avoid this, as it'll be very difficult to debug, mainly if users choose resolvers where catalog could be used, but don't use the <catalog/> option from the plugin.

**Comment by cmarchand** [comment]
1.5.1-RC5
Give a try and tell me, I have no way to unit test it, as I have no other URI resolver available.
I think I won't document it.
Best,
Christophe

**Comment by cmarchand** [comment]
1.5.1-RC6

**Comment by cmarchand** [comment]
@julienguiraud could you try 1.5.1-RC6 and check if it solves your problem ?
Best,
Christophe

**Comment by julienguiraud** [comment]
@cmarchand  Sorry for the late reply. I try it but it did not solve my problem due to another error further.
Due to lack of time and productive way to debug it, I revert back to a more classical catalog file.
Thanks for your support.
Julien
